stages:
  fetch_data:
    cmd: gsutil cp gs://gofind-datalake/dvc/chicago-crime.csv data/chicago-crime.csv
    deps:
    - gs://gofind-datalake/dvc/chicago-crime.csv
    outs:
    - data/chicago-crime.csv
  prepare:
    cmd: python src/prepare.py data/chicago-crime.csv
    deps:
    - data/chicago-crime.csv
    - src/prepare.py
    params:
    - prepare.split
    - prepare.validate
    outs:
    - data/chicago-test.csv
    - data/chicago-train.csv
    - data/chicago-val.csv
  train:
    cmd: python src/train.py data/chicago-train.csv data/chicago-val.csv
    deps:
    - data/chicago-train.csv
    - data/chicago-val.csv
    - src/train.py
    params:
    - train.batch_size
    - train.ds_epoch
    - train.epoch
    - train.label
    outs:
    - model/
    metrics:
    - metrics.json:
        cache: false
  evaluate:
    cmd: python src/evaluate.py data/chicago-test.csv model baseline.json
    deps:
    - data/chicago-test.csv
    - model/
    - src/evaluate.py
    params:
    - evaluate.batch_size
    - evaluate.label
    outs:
    - serving/
